server:
  port: 9091

spring:
  security:
    user:
      name: eslam
      password: eslam123
  application:
    name: spring-boot-907
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    username: hr
    password: hr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    baseName: i18n/messages


token:
  secret: kjdshfdjksh@#@$$#@dnsd!23223WE@#@#@asd
  time: 24h